### ISSUE TITLE
I get this error when I use explorer theme

### ISSUE THREAD

**Issue by JithinKS97** [frontend-collective/react-sortable-tree-theme-file-explorer#15]
Warning: React does not recognize the `rowDirection` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `rowdirection` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by FileThemeNodeContentRenderer)
    in FileThemeNodeContentRenderer (created by DragSource(FileThemeNodeContentRenderer))
    in DragSource(FileThemeNodeContentRenderer) (created by Grid)
    in div (created by FileThemeTreeNodeRenderer)
    in FileThemeTreeNodeRenderer (created by DropTarget(FileThemeTreeNodeRenderer))
    in DropTarget(FileThemeTreeNodeRenderer) (created by Grid)
    in div (created by Grid)
    in div (created by Grid)
    in Grid (created by List)
    in List (created by Scrolling(List))
    in Scrolling(List) (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by ReactSortableTree)
    in div (created by ReactSortableTree)
    in ReactSortableTree (created by DragDropContext(ReactSortableTree))

There isn't any problem when I just use the default one. However the app is not breaking. Is there any way to resolve this?

**Comment by Jongkeun** [comment]
Me too. 
@fritz-c, Could you check it?

**Comment by mahammedzkhan** [comment]
Quick fix is to downgrade the `react-sortable-tree` package to `^1.5.2`, you won't get any warnings anymore.

**Comment by Jongkeun** [comment]
@mahammedzkhan Thanks.

**Comment by mahammedzkhan** [comment]
I've made a PR with a proper fix which is compatible with `react-sortable-tree ^2.2.0` (latest version)

**Comment by devv-aman** [comment]
I'm still getting that warning and I'm using the latest version i.e 2.2.0

**Comment by 7ruth** [comment]
I am getting the same error with  "react-sortable-tree": "^2.2.0"
