### ISSUE TITLE
Incorrect package name in readme

### ISSUE THREAD

**Issue by OP-Mate** [frontend-collective/react-sortable-tree-theme-file-explorer#2]
Currently show's 

import FileExplorerTheme from 'react-sortable-tree-file-explorer-theme';

Needs to be 

import FileExplorerTheme from 'react-sortable-theme-tree-file-explorer';

**Comment by AstroCX1** [comment]
Should it not be "react-sortable-tree-theme-file-explorer"?

That what worked for me.

**Comment by fritz-c** [comment]
Ah, true. Thanks for catching this!
