### ISSUE TITLE
The drop area is located quite far to the right

### ISSUE THREAD

**Issue by JWaldenback** [frontend-collective/react-sortable-tree-theme-file-explorer#4]
Hi fritz-c!

Thank you for creating this theme, it's highly appreciated. 

I'm reopening this issue with canDrop. The drop area is located quite far to the right and not where it should be.

**Comment by fritz-c** [comment]
I think I know what you're talking about here, but could you try to get a screenshot of it so I know we're on the same page?

**Comment by JWaldenback** [comment]
Absolutely. 

In the picture below I’m trying to drop a node on level 6 but the plugin seems to think I'm trying to drop the node on level 1.
![image](https://user-images.githubusercontent.com/19432538/32303292-e6e38248-bf67-11e7-9f98-46ebad949d1a.png)


To be able to drop the node on level 6 I need to move it to the right.
![image](https://user-images.githubusercontent.com/19432538/32303281-dbaeb9c4-bf67-11e7-9e0b-2950c9ef0090.png)

Thank you!

**Comment by fritz-c** [comment]
Yep, that’s the one. Thanks for the screenshot. 

I think it’s a problem with react-sortable-tree itself, as I was only ever working with the one handle approach, never considering these full-width dragging ones. I’ll see over the weekend whether that’s an easy fix or not.

**Comment by JWaldenback** [comment]
I understand. 

If it’s difficult to do this, maybe you could make the original theme more compact? I believe this is what the others who’ve asked about a more compact theme have had in mind. And it’s probably easier for you to make as well!

Look at the two pictures below. The right one is more compact and displays the same information as the left one in almost half the space.
![image](https://user-images.githubusercontent.com/19432538/32365076-99c33b90-c078-11e7-8eb1-786963d70bd8.png)

**Comment by fritz-c** [comment]
The offset issue should now be fixed. You can check using the latest versions of the libraries.

**Comment by JWaldenback** [comment]
Thank you!
